name: CI

on: [push, pull_request]

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - uses: pre-commit/action@v1.1.0

    - name: Build Teyit
      run: python setup.py sdist

    - name: Run teyit
      run: python -m pip install pytest && python -m pytest

    - name: Publish
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}

  cpython:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: python/cpython

    - name: Install Dependencies
      run: sudo ./.github/workflows/posix-deps-apt.sh

    - name: Configure CPython
      run: ./configure --with-pydebug

    - name: Build CPython
      run: make -j8

    - uses: actions/checkout@v2
      with:
        path: teyit

    - name: Run Teyit on Tests
      run: ./python teyit/teyit.py Lib/test --show-stats

    - name: Tests
      run: ./python -m test -j8 $(git diff --name-only -- Lib/test | ./python -c "import sys;print(*[file.removeprefix('Lib/test/').removesuffix('.py') for file in sys.stdin.read().splitlines()], sep=' ')")
